// firebase-data.js — Auto-generated by Nick Admin Panel
// Place this in your GitHub Pages repo root.
// Add <script src="firebase-data.js"></script> before </body> in art.html and crochet.html
//
// HOW IT WORKS:
//   - Text data (about, pricing, gallery details) is stored in Firebase Firestore
//   - Images are stored on Cloudinary — Firestore just holds the https://res.cloudinary.com/... URL
//   - This script loads both and injects them into the page on every visit

(async function() {
  const firebaseCfg = {
    "apiKey": "AIzaSyAmT_H_IYhi8yq6SEylCou8KNd6mL4KS78",
    "authDomain": "nick-e0e1b.firebaseapp.com",
    "projectId": "nick-e0e1b",
    "messagingSenderId": "645278409923",
    "appId": "1:645278409923:web:9b16724e9e853be4236e76"
};

  const loadScript = src => new Promise(res => {
    const s = document.createElement('script');
    s.src = src; s.onload = res; document.head.appendChild(s);
  });
  await loadScript('https://www.gstatic.com/firebasejs/9.23.0/firebase-app-compat.js');
  await loadScript('https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore-compat.js');

  if (!firebase.apps.length) firebase.initializeApp(firebaseCfg);
  const db = firebase.firestore();

  const isArt = document.title.toLowerCase().includes('drawer') || location.pathname.includes('art');
  const page  = isArt ? 'art' : 'crochet';

  async function getDoc(col, docId) {
    try { const s = await db.collection(col).doc(docId).get(); return s.exists ? s.data() : null; }
    catch(e) { console.warn('Firestore read error', e); return null; }
  }
  async function getList(col) {
    try {
      const s = await db.collection(col).orderBy('createdAt', 'desc').get();
      return s.docs.map(d => ({ id: d.id, ...d.data() }));
    } catch(e) { return []; }
  }

  const [profile, about, contact, pricing, gallery, categories] = await Promise.all([
    getDoc(page + '_config', 'profile'),
    getDoc(page + '_config', 'about'),
    getDoc(page + '_config', 'contact'),
    getList(page + '_pricing'),
    getList(page + '_gallery'),
    getDoc(page + '_config', 'categories'),
  ]);

  // ---- Profile (avatar URL is a Cloudinary https:// URL stored in Firestore) ----
  if (profile) {
    document.querySelectorAll('[data-nick="name"]').forEach(el => el.textContent = profile.name || '');
    // Avatar: Cloudinary URL → set as <img> src
    if (profile.avatarUrl) {
      document.querySelectorAll('[data-nick="avatar"]').forEach(el => { el.src = profile.avatarUrl; });
    }
    if (profile.pageTitle) document.title = profile.pageTitle;
  }

  // ---- About ----
  if (about) {
    document.querySelectorAll('[data-nick="about-heading"]').forEach(el => el.textContent = about.heading || '');
    document.querySelectorAll('[data-nick="about-bio1"]').forEach(el => el.textContent = about.bio1 || '');
    document.querySelectorAll('[data-nick="about-bio2"]').forEach(el => el.textContent = about.bio2 || '');
    const tagsEl = document.querySelector('[data-nick="about-tags"]');
    if (tagsEl && about.tags) {
      tagsEl.innerHTML = about.tags.map(t => `<span class="tag">${t}</span>`).join('');
    }
  }

  // ---- Contact ----
  if (contact) {
    document.querySelectorAll('[data-nick="insta-url"]').forEach(el => el.href = contact.instagram || '#');
    document.querySelectorAll('[data-nick="fb-url"]').forEach(el => el.href = contact.facebook || '#');
    // Display name: show discordName if set, otherwise show a friendly fallback (never show raw ID)
    const discordId = (contact.discord || '').trim();
    const discordDisplay = (contact.discordName || '').trim();
    document.querySelectorAll('[data-nick="discord"]').forEach(el => {
      el.textContent = discordDisplay || (discordId ? 'Discord' : '');
    });
    // Set Discord link href using user ID (always a string of digits)
    document.querySelectorAll('#discordLink').forEach(el => {
      if (discordId) {
        el.href = 'https://discord.com/users/' + discordId;
        el.target = '_blank';
        el.rel = 'noopener noreferrer';
      } else {
        el.removeAttribute('href');
      }
    });
    document.querySelectorAll('[data-nick="contact-note"]').forEach(el => el.textContent = contact.note || '');
  }

  // ---- Pricing ----
  const pricingEl = document.querySelector('[data-nick="pricingGrid"]');
  if (pricingEl && pricing.length) {
    const isGreen = !isArt;
    const accentColor       = isGreen ? '#3a8a6e' : '#c4607a';
    const featuredBadgeLabel = isGreen ? 'Most Loved' : 'Popular';
    const featuredBadgeBg    = isGreen ? 'linear-gradient(135deg,#5aaa88,#3a8a6e)' : 'linear-gradient(135deg,#e8829a,#c4607a)';

    pricingEl.innerHTML = pricing.map(tier => `
      <div class="price-card${tier.featured ? ' featured' : ''}">
        ${tier.featured ? `<div class="featured-badge" style="background:${featuredBadgeBg}">${featuredBadgeLabel}</div>` : ''}
        <div class="price-icon" style="font-size:2.2rem">${tier.icon || '◆'}</div>
        <div class="price-type">${tier.name || ''}</div>
        <div class="price-desc">${tier.desc || ''}</div>
        <div class="price-amount" style="color:${accentColor}">${tier.price || ''}${tier.suffix ? ` <span>${tier.suffix}</span>` : ''}</div>
        ${tier.features && tier.features.length ? `
          <ul class="price-features">
            ${tier.features.map(f => `<li>${f}</li>`).join('')}
          </ul>` : ''}
      </div>`
    ).join('');
  }

  // ---- Gallery / Shop ----
  // imageUrl in each Firestore doc is a permanent Cloudinary CDN URL like:
  //   https://res.cloudinary.com/YOURCLOUD/image/upload/v123/nick/gallery/abc.jpg
  // Cloudinary serves it fast worldwide via their CDN — no extra cost on free plan.
  const galleryEl = document.getElementById(isArt ? 'galleryGrid' : 'shopGrid');
  if (galleryEl && gallery.length) {
    galleryEl.innerHTML = ''; // clear CSS placeholder art
    gallery.forEach(item => {
      const card = document.createElement('div');
      card.className = isArt ? 'gallery-item' : 'shop-card';
      card.dataset.cat = (item.cat || '').toLowerCase().replace(/\s+/g, '-');

      if (isArt) {
        // Frame inherits image natural size
        card.innerHTML = `
          <div class="gallery-frame">
            <img class="gallery-img"
                 src="${item.imageUrl}"
                 alt="${item.title}"
                 style="width:100%;display:block;border-radius:6px;"
                 loading="lazy"/>
            <div class="gallery-caption">${item.title}</div>
          </div>
          <div class="gallery-overlay">
            <div class="gallery-overlay-content">
              <span class="gallery-overlay-title">${item.title}</span>
              <span class="gallery-overlay-cat">${item.cat || ''}</span>
            </div>
          </div>`;
      } else {
        const avail = item.available !== false;
        card.innerHTML = `
          ${!avail ? '<div class="ribbon-sold">Sold Out</div>' : '<div class="badge-avail">Available</div>'}
          <div class="shop-img-wrap">
            <img src="${item.imageUrl}" alt="${item.title}"
                 style="width:100%;display:block;" loading="lazy"/>
          </div>
          <div class="shop-info">
            <div class="shop-name">${item.title}</div>
            <div class="shop-cat">${item.cat || ''}</div>
            <div class="shop-desc">${(item.desc || '').slice(0, 90)}${(item.desc || '').length > 90 ? '…' : ''}</div>
            <div class="shop-footer">
              <div class="shop-price ${avail ? '' : 'sold'}">$${item.price || 0}</div>
              <button class="shop-buy" ${avail ? '' : 'disabled'}
                onclick="window._orderItem && window._orderItem(${JSON.stringify(item).replace(/"/g,'&quot;')})">
                ${avail ? 'Order ✦' : 'Sold Out'}
              </button>
            </div>
          </div>`;
      }
      galleryEl.appendChild(card);
    });
  }

  // ---- Categories → update filter buttons ----
  if (categories?.list && categories.list.length) {
    const filterWrap = document.querySelector('.gallery-filters, .shop-filters');
    if (filterWrap) {
      const allBtn = filterWrap.querySelector('[data-filter="all"]');
      // Remove all category buttons except "All"
      filterWrap.querySelectorAll('[data-filter]:not([data-filter="all"])').forEach(b => b.remove());
      categories.list.forEach(cat => {
        const btn = document.createElement('button');
        btn.className = 'filter-btn';
        btn.dataset.filter = cat.toLowerCase().replace(/\s+/g, '-');
        btn.textContent = cat;
        filterWrap.appendChild(btn);
      });
      // Re-attach filter click logic
      filterWrap.querySelectorAll('.filter-btn').forEach(btn => {
        btn.addEventListener('click', () => {
          filterWrap.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
          btn.classList.add('active');
          const f = btn.dataset.filter;
          document.querySelectorAll('.gallery-item, .shop-card').forEach(card => {
            card.style.display = (f === 'all' || card.dataset.cat === f) ? '' : 'none';
          });
        });
      });
    }
  }

  console.log('[Nick] ✦ Content loaded — Firestore (text) + Cloudinary (images)');
})();
